export const sectionTitles = {
  inicio: 'Inicio',
  desayuno: 'Desayunos',
  asiatico: 'Comida Asiática',
  contacto: 'Contacto',
};

export const properties = [
  // --- DESAYUNOS (Categoría 'desayuno') ---
  // Chilaquiles
  {
    id: 34,
    type: 'Chilaquiles',
    category: 'desayuno',
    price: 160,
    title: 'Chilaquiles',
    description: 'Decorados de queso cotija, crema, cebolla morada y aguacate , acompañados de frijol frito',
    columns: [
      {
        title: 'Salsas',
        items: [
          'Roja',
          'Verde',
          'Poblana (+$10)',
          'Especial (receta de la casa)',
          'Mole (+$10)',
          'Marimar (+$20)'
        ]
      },
      {
        title: 'Complementos',
        items: [
          'Huevos $35',
          'Chicharron $70',
          'Machaca $70',
          'Pollo $60',
          'Bistec Ranchero $70',
          'Carne Deshebrada $70'
        ]
      }
    ],
    image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=600&q=80',
  },
  {
    id: 7,
    type: 'Chilaquiles',
    category: 'desayuno',
    price: 290,
    title: 'Chilaquiles Marimar',
    description: 'Chilaquiles en cremosa salsa de pimientos, coronados con queso monterrey, crema y cebolla. Acompañados de camarones salteados en mantequilla, aguacate y frijoles fritos',
    image: 'https://images.unsplash.com/photo-1534080391025-a87b99a94124?w=600&q=80',
  },
  {
    id: 35,
    type: 'Chilaquiles',
    category: 'desayuno',
    price: 370,
    title: 'MexiSlam',
    description: 'Chilaquiles divorciados en salsa verde y roja , decorados de queso cotija, crema ,cebolla y fajitas de Rib eye, acompañados de aguacate, frijol frito, chile toreado y huevo estrellado',
    image: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=600&q=80',
  },
  {
    id: 8,
    type: 'Desayuno Fuerte',
    category: 'desayuno',
    price: 380,
    title: 'Desayuno Del Patron',
    description: '300gr de Ribeye acompañados de 2 huevos estrellados, frijoles fritos , queso panela asado, aguacate y papas y tortillas de tu elección',
    image: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=600&q=80',
  },

  // Hot Cakes & Waffles
  {
    id: 1,
    type: 'Hot Cakes & Waffles',
    category: 'desayuno',
    price: 180,
    title: 'Tradicionales',
    description: '3 hotcakes decorados con fruta de temporada. Pieza $55',
    image: '/images/menu_breakfast.png',
  },
  {
    id: 36,
    type: 'Hot Cakes & Waffles',
    category: 'desayuno',
    price: 220,
    title: 'De Elote',
    description: '3 hotcakes decorados de requeson, fruta y miel de abeja. Pieza $75',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80',
  },
  {
    id: 37,
    type: 'Hot Cakes & Waffles',
    category: 'desayuno',
    price: 210,
    title: 'ChocoChip',
    description: '3 hotcakes rellenos de chispas de chocolate, decorados de chocolate Hershey y mas chispas de chocolate. Pieza $75',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80',
  },
  {
    id: 38,
    type: 'Hot Cakes & Waffles',
    category: 'desayuno',
    price: 110,
    title: 'Desayuno Kid',
    description: 'Mini waffles en forma de animalitos acompañados de 2 complementos: Huevo • Fruta • Tocino • Salchipulpos',
    image: 'https://images.unsplash.com/photo-1562376502-6f769499c886?w=600&q=80',
  },
  {
    id: 39,
    type: 'Hot Cakes & Waffles',
    category: 'desayuno',
    price: 210,
    title: 'Combo waffle',
    description: '4 cuadros de Waffles , acompañados de huevo revuelto y salchichas fritas , incluye un jugo de naranja o un cafe. Pieza de Waffle $80',
    image: 'https://images.unsplash.com/photo-1562376502-6f769499c886?w=600&q=80',
  },
  {
    id: 40,
    type: 'Hot Cakes & Waffles',
    category: 'desayuno',
    price: 260,
    title: 'Grand Slam',
    description: 'incluye dos hotcakes tradicionales, tocino , huevos revueltos , fruta de temporada y jugo o cafe. De elote $300, De Choco chip $290. cualquier cambio en bebida tendra un costo extra',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&q=80',
  },

  // Especialidades & Guisos
  {
    id: 2,
    type: 'Especialidad Mexicana',
    category: 'desayuno',
    price: 225,
    title: 'Bistec Ranchero',
    description: 'Carne de res guisada con verduras, acompañado de arroz, frijoles fritos, queso panela y aguacate',
    image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=600&q=80',
  },
  {
    id: 3,
    type: 'Especialidad Mexicana',
    category: 'desayuno',
    price: 170,
    title: 'Chile Relleno',
    description: 'Chile Poblano relleno de queso Monterrey bañado en caldillo, acompañado de arroz y frijoles fritos',
    image: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=600&q=80',
  },
  {
    id: 4,
    type: 'Especialidad Mexicana',
    category: 'desayuno',
    price: 220,
    title: 'Chicharron al Guajillo',
    description: 'Chicharron prensado en chile guajillo, acompañado de frijol frito, queso panela y aguacate',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
  },
  {
    id: 16,
    type: 'Especialidad Mexicana',
    category: 'desayuno',
    price: 220,
    title: 'Orden de Machaca',
    description: 'Machaca estilo sonora , acompañada de frijoles fritos, queso panela y aguacate',
    image: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=600&q=80',
  },
  {
    id: 17,
    type: 'Especialidad Mexicana',
    category: 'desayuno',
    price: 225,
    title: 'Carne Deshebrada',
    description: 'Carne en chile colorado, acompañada de arroz, frijoles fritos, queso panela y aguacate',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
  },
  {
    id: 18,
    type: 'Burritos',
    category: 'desayuno',
    priceText: 'Orden $150 | Burrito $50',
    title: 'Orden de Burritos',
    description: '2 burritos del guiso de tu elección acompañado de 2 complementos a elegir',
    columns: [
      {
        title: 'Guisos',
        items: ['Bistec Ranchero', 'Chicharron', 'Carne deshebrada', 'Machaca']
      },
      {
        title: 'Complementos',
        items: ['Ensalada', 'Frijol frito', 'Papas fritas', 'Arroz']
      }
    ],
    image: 'https://images.unsplash.com/photo-1626700051175-6518c4793f4f?w=600&q=80',
  },

  // Omelettes
  {
    id: 20,
    type: 'Omelette',
    category: 'desayuno',
    price: 200,
    title: 'Clasico',
    description: 'Relleno de jamón frito, tocino, queso Monterrey, acompañado de papas ,frijol y aguacate',
    image: 'https://images.unsplash.com/photo-1510627802777-3f91139be8f9?w=600&q=80',
  },
  {
    id: 21,
    type: 'Omelette',
    category: 'desayuno',
    price: 220,
    title: 'Supremo',
    description: 'Relleno de pimientos, champiñones,cebolla, chorizo español y queso monterrey acompañado de papas, frijol y aguacate',
    image: 'https://images.unsplash.com/photo-1510627802777-3f91139be8f9?w=600&q=80',
  },
  {
    id: 22,
    type: 'Omelette',
    category: 'desayuno',
    price: 220,
    title: 'Clarita',
    description: 'Omelette de claras relleno de espinacas, queso panela y jamon, acompañado de ensalada primavera (lechuga,espinaca, nuez, arandanos, apio y vinagreta de fresa)',
    image: 'https://images.unsplash.com/photo-1510627802777-3f91139be8f9?w=600&q=80',
  },
  {
    id: 23,
    type: 'Omelette',
    category: 'desayuno',
    price: 190,
    title: 'Veggie',
    description: 'Omelette Relleno tomate, espinaca, champiñones y queso Monterrey, acompañado de frijol y aguacate',
    image: 'https://images.unsplash.com/photo-1510627802777-3f91139be8f9?w=600&q=80',
  },
  {
    id: 6,
    type: 'Omelette',
    category: 'desayuno',
    price: 260,
    title: 'Premium',
    description: 'Relleno de tocino y queso Monterrey, decorado de camarones salteados en mantequilla y aderezo chipotle, acompañado de papas y aguacate',
    image: 'https://images.unsplash.com/photo-1494597564530-871f2b93ac55?w=600&q=80',
  },
  {
    id: 5,
    type: 'Omelette',
    category: 'desayuno',
    price: 240,
    title: 'Sonorense',
    description: 'Relleno de machaca hecha por nosotros y queso Monterrey , decorado de salsa tatemada, acompañado de frijol, queso panela asado , papas y aguacate',
    image: 'https://images.unsplash.com/photo-1510627802777-3f91139be8f9?w=600&q=80',
  },
  {
    id: 24,
    type: 'Desayuno Fuerte',
    category: 'desayuno',
    price: 275,
    title: 'Desayuno Selecto',
    description: 'Un desayuno completo: omelette relleno de jamón y queso Monterrey, acompañado de chilaquiles, frijoles y ensalada verde.',
    image: 'https://images.unsplash.com/photo-1510627802777-3f91139be8f9?w=600&q=80',
  },
  {
    id: 25,
    type: 'Especialidad Mexicana',
    category: 'desayuno',
    price: 200,
    title: 'Enmoladas',
    description: '3 tortillas rellenas de pollo , bañadas en mole chiapaneco, decoradas con crema , ajonjolí y queso panela, acompañadas de arroz',
    image: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=600&q=80',
  },
  {
    id: 26,
    type: 'Especialidad Mexicana',
    category: 'desayuno',
    price: 200,
    title: 'Enchiladas Suizas',
    description: '3 tortillas rellenas de pollo , bañadas en salsa poblana, decoradas de queso monterrey, crema y aguacate, acompañadas de arroz',
    image: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=600&q=80',
  },

  // --- COMIDA ASIÁTICA (Categoría 'asiatico') ---
  // Entradas
  {
    id: 42,
    type: 'Entrada Asiática',
    category: 'asiatico',
    price: 80,
    title: 'Oniguiris Dulces',
    description: '',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80',
  },
  {
    id: 43,
    type: 'Entrada Asiática',
    category: 'asiatico',
    price: 80,
    title: 'Rollos Primavera',
    description: '',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
  },
  {
    id: 15,
    type: 'Entrada Asiática',
    category: 'asiatico',
    price: 100,
    title: 'Gyozas',
    description: '',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80',
  },
  {
    id: 44,
    type: 'Entrada Asiática',
    category: 'asiatico',
    price: 140,
    title: 'Chiligyozas',
    description: '',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80',
  },

  // Yakimeshi
  {
    id: 45,
    type: 'Yakimeshi',
    category: 'asiatico',
    price: 120,
    title: 'Yakimeshi de Pollo',
    description: '',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80',
  },
  {
    id: 46,
    type: 'Yakimeshi',
    category: 'asiatico',
    price: 140,
    title: 'Yakimeshi de Res',
    description: '',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80',
  },
  {
    id: 47,
    type: 'Yakimeshi',
    category: 'asiatico',
    price: 110,
    title: 'Yakimeshi de Verduras',
    description: '',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80',
  },
  {
    id: 48,
    type: 'Yakimeshi',
    category: 'asiatico',
    price: 140,
    title: 'Yakimeshi de Camarón',
    description: '',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80',
  },
  {
    id: 49,
    type: 'Yakimeshi',
    category: 'asiatico',
    price: 140,
    title: 'Yakimeshi con Chorizo Chino',
    description: '',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80',
  },

  // Noodles
  {
    id: 62,
    type: 'Noodles',
    category: 'asiatico',
    price: 130,
    title: 'Noodles Salteados con Pollo',
    description: 'NOODLES SALTEADOS EN WOK , CON CEBOLLA Y REPOLLO MAS PROTEINA DE SU ELECCIÓN , BAÑADOS EN SALSAS ASIATICAS',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80',
  },
  {
    id: 14,
    type: 'Noodles',
    category: 'asiatico',
    price: 160,
    title: 'Noodles Salteados con Camarón',
    description: 'NOODLES SALTEADOS EN WOK , CON CEBOLLA Y REPOLLO MAS PROTEINA DE SU ELECCIÓN , BAÑADOS EN SALSAS ASIATICAS',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80',
  },
  {
    id: 63,
    type: 'Noodles',
    category: 'asiatico',
    price: 160,
    title: 'Noodles Salteados con Res',
    description: 'NOODLES SALTEADOS EN WOK , CON CEBOLLA Y REPOLLO MAS PROTEINA DE SU ELECCIÓN , BAÑADOS EN SALSAS ASIATICAS',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80',
  },
  {
    id: 64,
    type: 'Noodles',
    category: 'asiatico',
    price: 130,
    title: 'Macha Noodles de Pollo',
    description: 'NOODLES SALTEADOS EN WOK , CON CEBOLLA Y REPOLLO MAS PROTEINA DE SU ELECCIÓN BAÑADOS EN SALSAS NEGRAS Y MACHA',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80',
  },
  {
    id: 65,
    type: 'Noodles',
    category: 'asiatico',
    price: 160,
    title: 'Macha Noodles de Camarón',
    description: 'NOODLES SALTEADOS EN WOK , CON CEBOLLA Y REPOLLO MAS PROTEINA DE SU ELECCIÓN BAÑADOS EN SALSAS NEGRAS Y MACHA',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80',
  },
  {
    id: 66,
    type: 'Noodles',
    category: 'asiatico',
    price: 160,
    title: 'Macha Noodles de Res',
    description: 'NOODLES SALTEADOS EN WOK , CON CEBOLLA Y REPOLLO MAS PROTEINA DE SU ELECCIÓN BAÑADOS EN SALSAS NEGRAS Y MACHA',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80',
  },
  {
    id: 67,
    type: 'Noodles',
    category: 'asiatico',
    price: 160,
    title: 'Dan Dan Noodles con Porkbelly',
    description: 'NOODLES BAÑADOS EN SALSA A BASE DE CREMA DE CACAHUATE , DECORADO DE CEBOLLIN Y COMPLEMENTO A ELEGIR',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80',
  },
  {
    id: 68,
    type: 'Noodles',
    category: 'asiatico',
    price: 180,
    title: 'Dan Dan Noodles con Gyozas',
    description: 'NOODLES BAÑADOS EN SALSA A BASE DE CREMA DE CACAHUATE , DECORADO DE CEBOLLIN Y COMPLEMENTO A ELEGIR',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80',
  },
  {
    id: 69,
    type: 'Noodles',
    category: 'asiatico',
    price: 170,
    title: 'Chilly Noodles con Gyozas',
    description: 'NOODLES BAÑADOS DE ADEREZO ESPECIAL DE CHILE SECO CON UN TOQUE AGRIDULCE ADORNADO DE CILANTRO,CEBOLLÍN Y EL COMPLEMENTO DE TU ELECCION',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80',
  },
  {
    id: 70,
    type: 'Noodles',
    category: 'asiatico',
    price: 160,
    title: 'Chilly Noodles con Porkbelly',
    description: 'NOODLES BAÑADOS DE ADEREZO ESPECIAL DE CHILE SECO CON UN TOQUE AGRIDULCE ADORNADO DE CILANTRO,CEBOLLÍN Y EL COMPLEMENTO DE TU ELECCION',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80',
  },

  // Sushi
  {
    id: 50,
    type: 'Sushi Natural',
    category: 'asiatico',
    price: 165,
    title: 'Cali Delux',
    description: 'ROLLO FRESCO, POR DENTRO ALGA ,QUESO CREMA, AGUACATE , PEPINO Y CAMARON, FORRADO DE TAMPICO, CAMARON Y AGUACATE ,BAÑADO EN SALSA ANGUILA Y AJONJOLI NEGRO',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80',
  },
  {
    id: 51,
    type: 'Sushi Empanizado',
    category: 'asiatico',
    price: 170,
    title: 'Cielo, Mar y Tierra',
    description: 'ROLLO EMPANIZADO ,POR DENTRO ALGA, CAMARON, CARNE DE RES, POLLO,AGUACATE Y QUESO CREMA, BAÑADO DE CHIPOTLE Y SALSA ANGUILA',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80',
  },
  {
    id: 52,
    type: 'Sushi Empanizado',
    category: 'asiatico',
    price: 200,
    title: 'Dragon Roll',
    description: 'ROLLO FORRADO DE ALGA Y EMPANIZADO, POR DENTRO AGUACATE, QUESO CREMA, PEPINO, TAMPICO, CAMARON Y FURIKAKE, BAÑADO DE SALSA SIRRACHA Y SALSA ANGUILA, DECORADO CON CEBOLLIN',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80',
  },
  {
    id: 53,
    type: 'Sushi Gratinado',
    category: 'asiatico',
    price: 220,
    title: 'Chizu',
    description: 'ROLLO EMPANIZADO ,POR DENTRO ALGA, CAMARON, AGUACATE , QUESO CREMA, Y PEPINO , GRATINADO DE QUESO SPICY Y ADORNADO DE CAMARON, TOCINO Y CEBOLLIN , BAÑADO EN SALSA ANGUILA',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80',
  },

  // Combos & Ramen
  {
    id: 71,
    type: 'Bento Box',
    category: 'asiatico',
    price: 160,
    title: 'Combos',
    description: 'INCLUYE: TE CHICO, ARROZ FRITO, ROLLO PRIMAVERA Y PLATILLO A ESCOGER. PLATILLOS: HORONIGAI, TERIYAKI, BROCOLI CON PROTEINA, NOODLES DE POLLO, POLLO MONGOL',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
  },
  {
    id: 13,
    type: 'Ramen',
    category: 'asiatico',
    price: 200,
    title: 'Shoyu',
    description: 'FIDEOS EN CALDO DE CERDO COCIDO POR HORAS, REALZADO CON HUEVO MARINADO, ACOMPAÑADO DE PORKBELLY, CEBOLLIN, HONGO SHITAKE Y GERMINADO DE SOYA',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
  },
  {
    id: 72,
    type: 'Ramen',
    category: 'asiatico',
    price: 210,
    title: 'Miso',
    description: 'FIDEOS EN CALDO DE CERDO COCIDO POR HORAS, REALZADO CON HUEVO MARINADO, ACOMPAÑADO DE PORKBELLY, CEBOLLIN, HONGO SHITAKE Y GERMINADO DE SOYA',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
  },
  {
    id: 73,
    type: 'Ramen',
    category: 'asiatico',
    price: 220,
    title: 'Spicy Ramen',
    description: 'FIDEOS EN CALDO DE CERDO COCIDO POR HORAS, CON BASE DE SPICY MISO REALZADO CON HUEVO MARINADO, ACOMPAÑADO DE PORKBELLY, CEBOLLIN, HONGO SHITAKE , ALGA , NARUTO Y GERMINADO DE SOYA',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
  },

  // Especialidades Asiáticas
  {
    id: 74,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 150,
    title: 'Horonigai de Pollo',
    description: 'BOLITAS CAPEADAS DE LA PROTEINA DE TU ELECCION , SALTEADAS CON CEBOLLA, CHILE MORRON Y ZANAHORIA EN SALSA AGRIDULCE',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 75,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 190,
    title: 'Horonigai de Camarón',
    description: 'BOLITAS CAPEADAS DE LA PROTEINA DE TU ELECCION , SALTEADAS CON CEBOLLA, CHILE MORRON Y ZANAHORIA EN SALSA AGRIDULCE',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 76,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 150,
    title: 'Horonigai de Limón (Pollo)',
    description: 'BOLITAS CAPEADAS DE LA PROTEINA DE TU ELECCION , SALTEADAS CON CEBOLLIN EN SALSA AGRIDULCE DE LIMON',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 77,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 190,
    title: 'Horonigai de Limón (Camarón)',
    description: 'BOLITAS CAPEADAS DE LA PROTEINA DE TU ELECCION , SALTEADAS CON CEBOLLIN EN SALSA AGRIDULCE DE LIMON',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 78,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 150,
    title: 'Pollo Kung Pao',
    description: 'PROTEINA MARINADA CON SAKE Y SOYA, SALTEADO CON CACAHUATE , CEBOLLA Y CHILE , ACOMPAÑADO DE ARROZ FRITO',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 79,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 190,
    title: 'Camarón Kung Pao',
    description: 'PROTEINA MARINADA CON SAKE Y SOYA, SALTEADO CON CACAHUATE , CEBOLLA Y CHILE , ACOMPAÑADO DE ARROZ FRITO',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 80,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 150,
    title: 'Douban de Pollo',
    description: 'PROTEINA CAPEADA A ELEGIR, SALTEADA EN SALSA PAD THAI , CON FRIJOL CHINO, MORRON , CHILE Y ZANAHORIA',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 81,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 190,
    title: 'Douban de Res',
    description: 'PROTEINA CAPEADA A ELEGIR, SALTEADA EN SALSA PAD THAI , CON FRIJOL CHINO, MORRON , CHILE Y ZANAHORIA',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 82,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 140,
    title: 'Pollo Mongol',
    description: 'PROTEINA A ELEGIR , SALTEADA CON CHILE PICO DE PAJARO, APIO, CEBOLLIN EN SALSA ESPECIAL',
    image: '/images/menu_asian_chicken.png',
  },
  {
    id: 83,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 190,
    title: 'Res Mongol',
    description: 'PROTEINA A ELEGIR , SALTEADA CON CHILE PICO DE PAJARO, APIO, CEBOLLIN EN SALSA ESPECIAL',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 84,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 190,
    title: 'Camarón Mongol',
    description: 'PROTEINA A ELEGIR , SALTEADA CON CHILE PICO DE PAJARO, APIO, CEBOLLIN EN SALSA ESPECIAL',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 85,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 140,
    title: 'Brócoli con Pollo',
    description: 'PROTEINA SALTEADA CON BROCOLI, APIO Y CEBOLLA EN SALSA DE OSTION, ACOMPAÑADO DE ARROZ FRITO',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 86,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 190,
    title: 'Brócoli con Res',
    description: 'PROTEINA SALTEADA CON BROCOLI, APIO Y CEBOLLA EN SALSA DE OSTION, ACOMPAÑADO DE ARROZ FRITO',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 87,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 190,
    title: 'Brócoli con Camarón',
    description: 'PROTEINA SALTEADA CON BROCOLI, APIO Y CEBOLLA EN SALSA DE OSTION, ACOMPAÑADO DE ARROZ FRITO',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 88,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 150,
    title: 'Pollo Honey Butter',
    description: 'POLLO CAPEADO BAÑADO EN SALSA DE LA CASA CON UN TOQUE DE MIEL A BASE DE MANTEQUILLA',
    image: '/images/menu_asian_chicken.png',
  },
  {
    id: 89,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 150,
    title: 'Almendrado de Pollo',
    description: 'POLLO O CHORIZO SALTEADO CON APIO, ZANAHORIA, JICAMA , ALMENDRAS, NUEZ DE LA INDIA Y CACAHUATE , ACOMPAÑADO DE ARROZ FRITO',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 90,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 160,
    title: 'Almendrado de Chorizo Chino',
    description: 'POLLO O CHORIZO SALTEADO CON APIO, ZANAHORIA, JICAMA , ALMENDRAS, NUEZ DE LA INDIA Y CACAHUATE , ACOMPAÑADO DE ARROZ FRITO',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
  },
  {
    id: 91,
    type: 'Especialidad Asiática',
    category: 'asiatico',
    price: 200,
    title: 'Yaki Shifudo',
    description: 'MEZCLA DE CAMARON Y PESCADO EMPAPELADO CON APIO, CEBOLLA Y CHILE WERITO',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80',
  },

  // Teriyaki & Bento Box
  {
    id: 12,
    type: 'Teriyaki',
    category: 'asiatico',
    price: 130,
    title: 'Teriyaki de Pollo',
    description: 'PROTEINA A LA PLANCHA, SOBRE UNA CAMA DE ARROZ BLANCO, BAÑADA EN SALSA TERIYAKI, DECORADO DE CEBOLLIN Y AJONJOLI NEGRO',
    image: '/images/menu_asian_chicken.png',
  },
  {
    id: 54,
    type: 'Teriyaki',
    category: 'asiatico',
    price: 180,
    title: 'Teriyaki de Camarón',
    description: 'PROTEINA A LA PLANCHA, SOBRE UNA CAMA DE ARROZ BLANCO, BAÑADA EN SALSA TERIYAKI, DECORADO DE CEBOLLIN Y AJONJOLI NEGRO',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80',
  },
  {
    id: 55,
    type: 'Teriyaki',
    category: 'asiatico',
    price: 170,
    title: 'Teriyaki de Res',
    description: 'PROTEINA A LA PLANCHA, SOBRE UNA CAMA DE ARROZ BLANCO, BAÑADA EN SALSA TERIYAKI, DECORADO DE CEBOLLIN Y AJONJOLI NEGRO',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80',
  },
  {
    id: 56,
    type: 'Teriyaki',
    category: 'asiatico',
    price: 140,
    title: 'Teriyaki de Verduras',
    description: 'PROTEINA A LA PLANCHA, SOBRE UNA CAMA DE ARROZ BLANCO, BAÑADA EN SALSA TERIYAKI, DECORADO DE CEBOLLIN Y AJONJOLI NEGRO',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80',
  },
  {
    id: 57,
    type: 'Teriyaki',
    category: 'asiatico',
    price: 180,
    title: 'Teriyaki Cielo, Mar y Tierra',
    description: 'PROTEINA A LA PLANCHA, SOBRE UNA CAMA DE ARROZ BLANCO, BAÑADA EN SALSA TERIYAKI, DECORADO DE CEBOLLIN Y AJONJOLI NEGRO',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80',
  },
  {
    id: 58,
    type: 'Teriyaki',
    category: 'asiatico',
    price: 130,
    title: 'Pollo Yakitori',
    description: 'POLLO A LA PLANCHA CON APIO , CEBOLLA Y PONZU ACOMPAÑADO DE ARROZ FRITO',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80',
  },
  {
    id: 59,
    type: 'Bento Box',
    category: 'asiatico',
    price: 170,
    title: 'Bento Box #1 (Teriyaki)',
    description: '1 TERIYAKI: 2 ROLLOS PRIMAVERA Y 1 BAO, ARROZ BLANCO Y ENSALADA',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
  },
  {
    id: 60,
    type: 'Bento Box',
    category: 'asiatico',
    price: 170,
    title: 'Bento Box #2 (Noodles de Pollo)',
    description: '2 NOODLES DE POLLO: 2 GYOZAS Y 1 ONIGUIRI, ENSALADA',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
  },
  {
    id: 61,
    type: 'Bento Box',
    category: 'asiatico',
    price: 170,
    title: 'Bento Box #3 (Horonigai)',
    description: '3 HORONIGAI DE POLLO: 1 ROLLO PRIMAVERA, 1 GYOZA Y 1 BAO, ARROZ FRITO Y ENSALADA',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
  },

  // Menú Kids
  {
    id: 92,
    type: 'Menú Kids',
    category: 'asiatico',
    price: 100,
    title: 'Menú Kids #1 (Pollo Teriyaki)',
    description: 'POLLO TERIYAKI Y ONIGIRI EN FORMA DE GATITO',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
  },
  {
    id: 93,
    type: 'Menú Kids',
    category: 'asiatico',
    price: 100,
    title: 'Menú Kids #2 (Nuggets de Pollo)',
    description: 'NUGGETS DE POLLO Y ONIGIRI EN FORMA DE GATITO',
    image: 'https://images.unsplash.com/photo-1562376502-6f769499c886?w=600&q=80',
  },
  // Té Chino en Comida Asiática
  {
    id: 94,
    type: 'Entrada Asiática',
    category: 'asiatico',
    priceText: 'Chico $30 | Grande $50',
    title: 'Te Chino',
    description: '',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
  },
  // Toasts y Opciones Saludables (Desayunos)
  {
    id: 11,
    type: 'Fruta & Saludable',
    category: 'desayuno',
    price: 150,
    title: 'Bowl de Frutas',
    description: 'Fruta de temporada adornada de yogur natural, granola y miel de abeja',
    image: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600&q=80',
  },
  {
    id: 41,
    type: 'Toast / Masa Madre',
    category: 'desayuno',
    price: 170,
    title: 'Avocado Toast',
    description: 'Toast con cubierta de aguacate, espinaca, tomate, queso panela coronado con huevo estrellado o revuelto',
    image: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=600&q=80',
  },
  {
    id: 9,
    type: 'Toast / Masa Madre',
    category: 'desayuno',
    price: 210,
    title: 'Macha Toast',
    description: 'Toast cubierta de aguacate, huevo revuellto con queso monterrey y salsa macha, acompañada de ensalada primavera (lechuga,espinaca, nuez, arandanos, apio ,fruta de temporada y vinagreta)',
    image: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=600&q=80',
  },
  {
    id: 10,
    type: 'Toast / Masa Madre',
    category: 'desayuno',
    price: 170,
    title: 'Dulce Amanecer',
    description: 'Toast con requeson, piña asada caramelizada, gajos de naranja fresca y fresa, terminado con miel de abeja y arandanos',
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&q=80',
  }
];

export const beverages = [
  { name: 'Cafe (Refill)', price: 55, type: 'Cafetería' },
  { name: 'Cafe de olla', price: 60, type: 'Cafetería' },
  { name: 'Latte frio (vainilla o caramelo)', price: 80, type: 'Cafetería' },
  { name: 'Mokate (leche, crema de cacahuate, cafe y chocolate)', price: 90, type: 'Cafetería' },
  { name: 'Chocoplatano', price: 55, type: 'Licuados' },
  { name: 'Chocomilk', price: 55, type: 'Licuados' },
  { name: 'Licuado de fresa', price: 55, type: 'Licuados' },
  { name: 'Jugo de naranja', price: 50, type: 'Jugos Naturales' },
  { name: 'Jugo verde (naranja, apio, manzana, espinaca y piña)', price: 80, type: 'Jugos Naturales' },
  { name: 'Aguas frescas', price: 60, type: 'Bebidas Frías' },
  { name: 'Frutilicia (naranja, fresa y mango)', price: 65, type: 'Jugos Naturales' },
  { name: 'Soda', price: 45, type: 'Bebidas Frías' },
  { name: 'Botella de agua', price: 20, type: 'Bebidas Frías' },
];

export async function obtenerPlatillos() {
  return Promise.resolve(properties);
}

export async function obtenerPlatilloPorId(id) {
  const item = properties.find((p) => p.id === id);
  return Promise.resolve(item);
}

export async function obtenerPlatillosDestacados() {
  const all = await obtenerPlatillos();
  const breakfasts = all.filter(p => p.category === 'desayuno').slice(0, 2);
  const asians = all.filter(p => p.category === 'asiatico').slice(0, 2);
  return [...breakfasts, ...asians];
}

export async function obtenerPlatillosPorCategoria(category) {
  const all = await obtenerPlatillos();
  return all.filter(p => p.category === category);
}
